#!/bin/bash

for file in "$@"; do
  echo "SHA Checksum $(shasum "$file")"
  url="$(curl -# -L -T "$file" "https://chunk.herokuapp.com")"
  echo "$url"
  if which pbcopy > /dev/null; then
    echo -n "$url" | pbcopy
  elif which xclip > /dev/null; then
    echo -n "$url" | xclip -selection clipboard
  fi
  echo
  sleep 1
done